[package]
name = "sonarigo-lv2"
version = "0.1.0"
authors = ["Johannes Mueller <github@johannes-mueller.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lv2 = "0.6"
lv2-worker = "0.1"
wmidi = "3.1.0"

soundfonts = { path = "../soundfonts" }
